### ISSUE TITLE
github.com/roserocket/roserocket/utils in Private Repo

### ISSUE THREAD

**Issue by samkreter** [RoseRocket/gopartial#1]
Getting this error when trying to run the example:

```
../github.com/roserocket/gopartial/skipconditions.go:7:2: cannot find package "github.com/roserocket/roserocket/utils" in any of
```

Looks like there is a dep on github.com/roserocket/roserocket/utils but its in a private repo so it can't be cloned down.

**Comment by aluksidadi** [comment]
Hi Sam, thanks for reporting this. 

The fix is underway! https://github.com/RoseRocket/gopartial/pull/2

Will be merged later today

**Comment by aluksidadi** [comment]
Fix has been merged. let me know if you still have any issue. Thanks!
